//Menu
export const INIT_MENU = 'INIT_MENU';
export const SET_MENU_LIST = 'SET_MENU_LIST';
export const SET_MENU_LIST_FETCH = 'SET_MENU_LIST_FETCH'
export const SET_MENU_SELECTED_KEY = 'SET_MENU_SELECTED_KEY';
//Store
export const SET_STORE_DISPATCH = 'SET_STORE_DISPATCH';
//Login
export const SET_LOGIN = 'SET_LOGIN';
export const SET_LOGIN_USERNAME = 'SET_LOGIN_USERNAME';
export const SET_LOGIN_PASSWORD = 'SET_LOGIN_PASSWORD';
// Router
export const SET_ROUTER_HISTORY = 'SET_ROUTER_HISTORY'
// TitleBar
export const SET_PASSWORD_MODAL_VISIBLE = 'SET_PASSWORD_MODAL_VISIBLE'
export const SET_OLD_PASSWORD = 'SET_OLD_PASSWORD'
export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD'
// Mod
export const SET_MOD_LIST = 'SET_MOD_LIST'
export const SET_MOD_LIST_FETCH = 'SET_MOD_LIST_FETCH'
export const SET_MOD_CREATE_MODAL_VISIBLE = 'SET_MOD_CREATE_MODAL_VISIBLE'
export const SET_MOD_CREATE_MODAL_NAME = 'SET_MOD_CREATE_MODAL_NAME'
export const SET_MOD_CREATE_MODAL_SIGN = 'SET_MOD_CREATE_MODAL_SIGN'
export const SET_MOD_CREATE_MODAL_RANK = 'SET_MOD_CREATE_MODAL_RANK'
export const SET_MOD_CREATE_MODAL_URL_IDS = 'SET_MOD_CREATE_MODAL_URL_IDS'
export const SET_MOD_UPDATE_MODAL_VISIBLE = 'SET_MOD_UPDATE_MODAL_VISIBLE'
export const SET_MOD_UPDATE_MODAL_ID = 'SET_MOD_UPDATE_MODAL_ID'
export const SET_MOD_UPDATE_MODAL_NAME = 'SET_MOD_UPDATE_MODAL_NAME'
export const SET_MOD_UPDATE_MODAL_SIGN = 'SET_MOD_UPDATE_MODAL_SIGN'
export const SET_MOD_UPDATE_MODAL_RANK = 'SET_MOD_UPDATE_MODAL_RANK'
export const SET_MOD_UPDATE_MODAL_URL_IDS = 'SET_MOD_UPDATE_MODAL_URL_IDS'
// User
export const SET_USER_LIST = 'SET_USER_LIST'
export const SET_USER_LIST_FETCH = 'SET_USER_LIST_FETCH'
export const SET_USER_CREATE_MODAL_VISIBLE = 'SET_USER_CREATE_MODAL_VISIBLE'
export const SET_USER_CREATE_MODAL_USERNAME = 'SET_USER_CREATE_MODAL_USERNAME'
export const SET_USER_CREATE_MODAL_PASSWORD = 'SET_USER_CREATE_MODAL_PASSWORD'
export const SET_USER_CREATE_MODAL_NAME = 'SET_USER_CREATE_MODAL_NAME'
export const SET_USER_CREATE_MODAL_PHONE = 'SET_USER_CREATE_MODAL_PHONE'
export const SET_USER_CREATE_MODAL_EMAIL = 'SET_USER_CREATE_MODAL_EMAIL'
export const SET_USER_CREATE_MODAL_ROLE_IDS = 'SET_USER_CREATE_MODAL_ROLE_IDS'
export const SET_USER_UPDATE_MODAL_VISIBLE = 'SET_USER_UPDATE_MODAL_VISIBLE'
export const SET_USER_UPDATE_MODAL_ID = 'SET_USER_UPDATE_MODAL_ID'
export const SET_USER_UPDATE_MODAL_PASSWORD = 'SET_USER_UPDATE_MODAL_PASSWORD'
export const SET_USER_UPDATE_MODAL_NAME = 'SET_USER_UPDATE_MODAL_NAME'
export const SET_USER_UPDATE_MODAL_PHONE = 'SET_USER_UPDATE_MODAL_PHONE'
export const SET_USER_UPDATE_MODAL_EMAIL = 'SET_USER_UPDATE_MODAL_EMAIL'
export const SET_USER_UPDATE_MODAL_ROLE_IDS = 'SET_USER_UPDATE_MODAL_ROLE_IDS'
// Role
export const SET_ROLE_LIST = 'SET_ROLE_LIST'
export const SET_ROLE_LIST_FETCH = 'SET_ROLE_LIST_FETCH'
export const SET_ROLE_CREATE_MODAL_VISIBLE = 'SET_ROLE_CREATE_MODAL_VISIBLE'
export const SET_ROLE_CREATE_MODAL_NAME = 'SET_ROLE_CREATE_MODAL_NAME'
export const SET_ROLE_CREATE_MODAL_SIGN = 'SET_ROLE_CREATE_MODAL_SIGN'
export const SET_ROLE_CREATE_MODAL_MOD_IDS = 'SET_ROLE_CREATE_MODAL_MOD_IDS'
export const SET_ROLE_UPDATE_MODAL_VISIBLE = 'SET_ROLE_UPDATE_MODAL_VISIBLE'
export const SET_ROLE_UPDATE_MODAL_ID = 'SET_ROLE_UPDATE_MODAL_ID'
export const SET_ROLE_UPDATE_MODAL_NAME = 'SET_ROLE_UPDATE_MODAL_NAME'
export const SET_ROLE_UPDATE_MODAL_SIGN = 'SET_ROLE_UPDATE_MODAL_SIGN'
export const SET_ROLE_UPDATE_MODAL_MOD_IDS = 'SET_ROLE_UPDATE_MODAL_MOD_IDS'
// Url
export const SET_URL_LIST = 'SET_URL_LIST'
export const SET_URL_LIST_FETCH = 'SET_URL_LIST_FETCH'
export const SET_URL_CREATE_MODAL_VISIBLE = 'SET_URL_CREATE_MODAL_VISIBLE'
export const SET_URL_CREATE_MODAL_NAME = 'SET_URL_CREATE_MODAL_NAME'
export const SET_URL_CREATE_MODAL_URL = 'SET_URL_CREATE_MODAL_URL'
export const SET_URL_UPDATE_MODAL_VISIBLE = 'SET_URL_UPDATE_MODAL_VISIBLE'
export const SET_URL_UPDATE_MODAL_ID = 'SET_URL_UPDATE_MODAL_ID'
export const SET_URL_UPDATE_MODAL_NAME = 'SET_URL_UPDATE_MODAL_NAME'
export const SET_URL_UPDATE_MODAL_URL = 'SET_URL_UPDATE_MODAL_URL'

// 评价
export const SET_COMMENT_LIST = 'SET_COMMENT_LIST'
export const SET_COMMENT_LIST_FETCH = 'SET_COMMENT_LIST_FETCH'
export const SET_COMMENT_PAGE_NUM = 'SET_COMMENT_PAGE_NUM'
export const SET_COMMENT_PAGE_SIZE = 'SET_COMMENT_PAGE_SIZE'
export const SET_COMMENT_TOTAL = 'SET_COMMENT_TOTAL'
export const SET_COMMENT_FILTER_KEYWORD = 'SET_COMMENT_FILTER_KEYWORD'
export const SET_COMMENT_FILTER_LABEL = 'SET_COMMENT_FILTER_LABEL'
export const SET_COMMENT_FILTER_STATUS = 'SET_COMMENT_FILTER_STATUS'
// 停止词
export const SET_STOPWORD_LIST = 'SET_STOPWORD_LIST'
export const SET_STOPWORD_LIST_FETCH = 'SET_STOPWORD_LIST_FETCH'
export const SET_STOPWORD_PAGE_NUM = 'SET_STOPWORD_PAGE_NUM'
export const SET_STOPWORD_PAGE_SIZE = 'SET_STOPWORD_PAGE_SIZE'
export const SET_STOPWORD_TOTAL = 'SET_STOPWORD_TOTAL'
export const SET_STOPWORD_FILTER_KEYWORD = 'SET_STOPWORD_FILTER_KEYWORD'
export const SET_STOPWORD_FILTER_STATUS = 'SET_STOPWORD_FILTER_STATUS'
export const SET_STOPWORD_CREATE_MODAL_WORD = 'SET_STOPWORD_CREATE_MODAL_WORD'
export const SET_STOPWORD_CREATE_MODAL_VISIBLE = 'SET_STOPWORD_CREATE_MODAL_VISIBLE'