module.exports = {
    // 登录
    apiLogin: '/api/v1/account/login/',
    apiUserModList: '/api/v1/account/user/mod/list/',
    apiPasswordChange: '/api/v1/account/password/change/',
    // 角色
    apiRoleList: '/api/v1/account/role/list/',
    apiRoleCreate: '/api/v1/account/role/create/',
    apiRoleUpdate: '/api/v1/account/role/update/',
    apiRoleDelete: '/api/v1/account/role/delete/',
    // 模块
    apiModList: '/api/v1/account/mod/list/',
    apiModCreate: '/api/v1/account/mod/create/',
    apiModUpdate: '/api/v1/account/mod/update/',
    apiModDelete: '/api/v1/account/mod/delete/',
    // 用户
    apiUserList: '/api/v1/account/user/list/',
    apiUserCreate: '/api/v1/account/user/create/',
    apiUserUpdate: '/api/v1/account/user/update/',
    apiUserDelete: '/api/v1/account/user/delete/',
    // URL
    apiUrlList: '/api/v1/account/url/list/',
    apiUrlCreate: '/api/v1/account/url/create/',
    apiUrlUpdate: '/api/v1/account/url/update/',
    apiUrlDelete: '/api/v1/account/url/delete/',
    // 评价
    apiCommentList: '/api/v1/dataset/comment/list/',
    apiCommentUpdate: '/api/v1/dataset/comment/update/',
    apiCommentCheck: '/api/v1/dataset/comment/check/',
    // 停止词
    apiStopwordList: '/api/v1/dataset/stopword/list/',
    apiStopwordCreate: '/api/v1/dataset/stopword/create/',
    apiStopwordUpdate: '/api/v1/dataset/stopword/update/',
    apiStopwordDelete: '/api/v1/dataset/stopword/delete/',
}